### ISSUE TITLE
onnx probem

### ISSUE THREAD

**Issue by LopSdir** [codename0og/RVC_Onnx_Infer#4]
![image](https://github.com/codename0og/RVC_Onnx_Infer/assets/49876859/f3c475da-c5b5-4b5c-a9d5-001144ab1b8f)
I have this problem, May I know how to solve this problem. THank you

**Comment by codename0og** [comment]
Seems like the problem is your onnx model. The input shapes mismatch.
You can't use w-okada or newest rvc's exports or V1 based models ( Only V2 models are supported ). 
Try my personal fork, I've fixed the onnx exporter in there ( essentially reverted it to the last properly working version ) and it's what I use to obtain my onnx models.

https://github.com/codename0og/hifi_testing_new

**Comment by LopSdir** [comment]
thank you so much and I will yry it later





------------------ Original ------------------
From: Codename;0 ***@***.***&gt;
Date: Sat,Apr 20,2024 4:57 PM
To: codename0og/RVC_Onnx_Infer ***@***.***&gt;
Cc: LopSdir ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [codename0og/RVC_Onnx_Infer] onnx probem (Issue #4)





 
Seems like the problem is your onnx model. The input shapes mismatch.
 You can't use w-okada or newest rvc's exports.
 Try my personal fork, I've fixed the onnx exporter in there ( essentially reverted it to the last properly working version ) and it's what I use to obtain my onnx models.
 
https://github.com/codename0og/hifi_testing_new

**Comment by codename0og** [comment]
Sure thing man, no worries. If it still won't budge, let me know

**Comment by LopSdir** [comment]
It really works, thank you so much.

**Comment by codename0og** [comment]
I'm glad, have fun
